sources:
  docker:
    type: docker_logs
    include_containers:
      - product_service

transforms:
  docker_parse_json:
    type: remap
    inputs:
      - docker
    source: |
      . = parse_json!(.message)

sinks: 
  console_sink:
    type: console
    inputs:
      - docker_parse_json
    encoding:
      codec: json
  
  loki_sink:
    type: loki
    inputs:
      - docker_parse_json
    endpoint: http://loki:3100
    encoding:
      codec: json
    labels:
      service: "{{ Properties.service }}"
      level: "{{ Level }}"
      
